-- SQLite schema for TrustOS MVP trustee data.

CREATE TABLE IF NOT EXISTS trustees (
    id INTEGER PRIMARY KEY,
    trustee_name TEXT,
    minimum_assets INTEGER,
    fee_structure TEXT,
    jurisdiction TEXT,
    directed_trust_supported BOOLEAN,
    external_advisor_supported BOOLEAN,
    custodian_platform TEXT,
    asset_types_supported TEXT
);

INSERT INTO trustees (
    id,
    trustee_name,
    minimum_assets,
    fee_structure,
    jurisdiction,
    directed_trust_supported,
    external_advisor_supported,
    custodian_platform,
    asset_types_supported
) VALUES
    (1, 'Wealth Advisors Trust Company', 1000000, 'AUM-based annual fee (0.45%-0.85%)', 'South Dakota', 1, 1, 'Schwab', 'Marketable securities, cash, alternatives, private funds'),
    (2, 'Sterling Trustees', 500000, 'Tiered annual fee + account admin surcharge', 'Nevada', 1, 1, 'Fidelity', 'Marketable securities, cash, concentrated stock'),
    (3, 'Arden Trust', 750000, 'AUM-based annual fee (breakpoint schedule)', 'South Dakota', 1, 1, 'Schwab', 'Marketable securities, cash, private equity, real estate LLCs'),
    (4, 'Bridgeford Trust', 1000000, 'Flat trustee fee + specialty asset add-ons', 'South Dakota', 1, 1, 'Fidelity', 'Marketable securities, cash, alternatives, private notes'),
    (5, 'South Dakota Trust Company', 500000, 'Tiered annual fee with minimum annual billing', 'South Dakota', 1, 0, 'Multi-custodian', 'Marketable securities, cash, closely held business interests'),
    (6, 'National Advisors Trust', 250000, 'Flat + AUM hybrid fee', 'Kansas', 1, 1, 'Multi-custodian', 'Marketable securities, cash, private assets, alternatives'),
    (7, 'Members Trust Company', 1000000, 'AUM-based annual fee + trust administration fee', 'New Hampshire', 1, 1, 'Pershing', 'Marketable securities, cash, concentrated stock, fixed income'),
    (8, 'Cumberland Trust', 2500000, 'AUM + administration fee (family office style)', 'Tennessee', 0, 1, 'Multi-custodian', 'Marketable securities, cash, family business holdings, real estate'),
    (9, 'Peak Trust', 2000000, 'Custom negotiated fee based on complexity', 'Alaska', 1, 1, 'Schwab', 'Marketable securities, cash, real estate, alternatives, private equity'),
    (10, 'Alliance Trust Company of Nevada', 500000, 'Tiered AUM schedule + annual account minimum', 'Nevada', 1, 1, 'Schwab', 'Marketable securities, cash, private funds, alternative assets'),
    (11, 'Counsel Trust Company', 1000000, 'AUM-based annual fee with directed trust discount', 'New Hampshire', 1, 1, 'Fidelity', 'Marketable securities, cash, concentrated stock, limited partnerships'),
    (12, 'Independent Trust Company of America', 300000, 'Flat annual trustee fee + transaction charges', 'Nevada', 1, 1, 'Multi-custodian', 'Marketable securities, cash, annuities, alternatives'),
    (13, 'Pendleton Square Trust Company', 1000000, 'Tiered trust admin fee + AUM oversight fee', 'New Hampshire', 1, 1, 'Pershing', 'Marketable securities, cash, private business interests, real estate'),
    (14, 'Prairie Trust', 300000, 'Tiered annual fee', 'South Dakota', 1, 1, 'Schwab', 'Marketable securities, cash, private debt funds'),
    (15, 'Premier Trust', 500000, 'AUM-based annual fee + directed trust administration fee', 'Nevada', 1, 1, 'Fidelity', 'Marketable securities, cash, alternatives, digital assets via approved custodian'),
    (16, 'Commonwealth Trust Company', 1000000, 'AUM fee with fixed annual trust administration minimum', 'Wyoming', 1, 1, 'Schwab', 'Marketable securities, cash, private equity, oil and gas interests'),
    (17, 'Dunham Trust Company', 250000, 'Flat trustee fee + optional fiduciary oversight retainer', 'Nevada', 1, 1, 'Fidelity', 'Marketable securities, cash, alternatives, promissory notes'),
    (18, 'IQ-EQ Trust Services', 3000000, 'Complexity-based annual fee + custody passthrough', 'Delaware', 1, 1, 'Multi-custodian', 'Marketable securities, cash, private equity, hedge funds, global assets'),
    (19, 'Bryn Mawr Trust', 2000000, 'AUM-based annual fee with family office service tiers', 'Pennsylvania', 0, 1, 'BNY Pershing', 'Marketable securities, cash, fixed income, private investments'),
    (20, 'Capital First Trust Company', 500000, 'Tiered annual fee + special asset handling fees', 'South Dakota', 1, 1, 'Schwab', 'Marketable securities, cash, real estate, private placements'),
    (21, 'American Estate & Trust', 250000, 'Flat administration fee + low-balance surcharge', 'Nevada', 1, 1, 'Fidelity', 'Marketable securities, cash, insurance trusts, alternatives'),
    (22, 'TrustCorp America', 750000, 'AUM + trustee acceptance fee', 'Delaware', 1, 1, 'Multi-custodian', 'Marketable securities, cash, private debt, concentrated equity'),
    (23, 'BOK Financial Advisor Trust Services', 1000000, 'Tiered AUM fee for advisor-managed trust accounts', 'Kansas', 1, 1, 'BOK Financial / Multi-custodian', 'Marketable securities, cash, fixed income, alternatives'),
    (24, 'Cresset Trust', 5000000, 'Integrated wealth fee with trust administration component', 'South Dakota', 1, 1, 'Schwab / Fidelity', 'Marketable securities, cash, private equity, direct investments, real estate'),
    (25, 'Northern Plains Trust Company', 400000, 'Tiered annual fee + directed trust optional rider', 'South Dakota', 1, 1, 'Schwab', 'Marketable securities, cash, farmland, private partnerships'),
    (26, 'Summit Legacy Trust', 1500000, 'AUM-based annual fee + specialty asset review fees', 'Nevada', 1, 1, 'Fidelity', 'Marketable securities, cash, private funds, digital assets via qualified custodian'),
    (27, 'Harbor Point Trust Company', 800000, 'Flat + AUM hybrid fee with annual minimum', 'Delaware', 1, 1, 'Pershing', 'Marketable securities, cash, private credit, limited partnerships'),
    (28, 'Granite Ridge Trust', 600000, 'Tiered trustee administration fee', 'New Hampshire', 1, 0, 'Multi-custodian', 'Marketable securities, cash, annuities, alternative investments'),
    (29, 'Bluewater Fiduciary Trust', 1200000, 'AUM fee with bespoke family governance services', 'Wyoming', 1, 1, 'Schwab', 'Marketable securities, cash, private company shares, real estate'),
    (30, 'Sagebrush Trust Company', 350000, 'Flat annual trustee fee + directed trust discounts', 'Nevada', 1, 1, 'Fidelity', 'Marketable securities, cash, mineral rights, alternatives'),
    (31, 'Founders Trust Services', 900000, 'Tiered AUM fee with minimum annual charge', 'South Dakota', 1, 1, 'Schwab', 'Marketable securities, cash, private equity, concentrated stock'),
    (32, 'Liberty Crest Trust Company', 700000, 'AUM + account complexity adjustment', 'Delaware', 1, 1, 'BNY Pershing', 'Marketable securities, cash, hedge funds, private notes'),
    (33, 'Canyon State Trust', 450000, 'Flat administration fee + optional distribution services fee', 'Arizona', 0, 1, 'Multi-custodian', 'Marketable securities, cash, real estate, private business interests'),
    (34, 'Redwood Legacy Trust', 1800000, 'Family-office style annual retainer + AUM overlay', 'California', 1, 1, 'Fidelity', 'Marketable securities, cash, venture funds, private placements'),
    (35, 'Heritage Oak Trust Company', 550000, 'Tiered trustee fee + annual tax package fee', 'Tennessee', 1, 1, 'Schwab', 'Marketable securities, cash, closely held entities, alternatives'),
    (36, 'Silvergate Trust Services', 650000, 'AUM-based annual fee with directed trust support package', 'Alaska', 1, 1, 'Multi-custodian', 'Marketable securities, cash, private debt, real assets');
